# Assignment 1

## Objective of this assignment
The objective is to get acquainted with the Python language, with emphasis on its scientific and numerical extensions, how data can be imported from other data sources, the linear algebra basics that are needed for this course, visualization using principal component analysis (PCA) and the concept of similarity. Upon completing this exercise it is expected that you:

- Understand how data can be represented as vectors and matrices in numerical Python (NumPy).
- Can apply and interpret principal component analysis (PCA) for data visualization.
- Understand the various measures of similarity such as Jaccard and Cosine similarity and apply similarity measures to query for similar observations.

## ** Important: ** When handing in your homework:
+ Hand in the notebook (and nothing else) named as follows: `StudentName1_snumber_StudentName2_snumber.ipynb`
+ Provide clear and complete answers to the questions below under a separate header (not hidden somewhere in your source code), and make sure to explain your answers / motivate your choices. Add Markdown cells where necessary.
+ Source code, output graphs, derivations, etc., should be included in the notebook.
+ Hand-in: upload to Brightspace.
+ Include name, student number, assignment (especially in filenames)!
+ When working in pairs only one of you should upload the assignment, and report the name of your partner in your filename.
+ Use the Brightspace discussion board or email the student assistants for questions on how to complete the exercises.
+ If you find mistakes/have suggestions/would like to complain about the assigment material itself, please email me [Lisa] at `l.tostrams@science.ru.nl`


## Advised Reading and Exercise Material
**The following on-line materials are recommended:**

- <http://docs.python.org/tutorial> - Introduction into Python environment, syntax and data structures. Recommended reading - sections 1, 2, 3, 4 and 5.
- <https://docs.scipy.org/doc/numpy/user/quickstart.html> - Tutorial introducing the scientific computing in Python, array and matrix operations, indexing and slicing matrices.
- <https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html> - Useful reference to scientific computing in Python if you have previous experience with MATLAB programming.
- <https://www.datacamp.com/courses/intro-to-python-for-data-science> - Simple introduction to Data Science using Python.
- <https://matplotlib.org/> - Documentation and examples related to matplotlib module, which we shall use extensively through the course to visualize data and results.
- Pang-Ning Tan, Michael Steinbach, and Vipin Kumar, **Introduction to Data Mining**, sections 2.1-2.3 + (A) + B.1
- Pang-Ning Tan, Michael Steinbach, and Vipin Kumar, **Introduction to Data Mining**, sections 2.4 + 3.1-3.2 + C.1-C.2


## 1.1 Python and Linear Algebra basics

**For this course we advise to only use NumPy ndarrays to represent vectors and matrices. The numpy.matrix data type, although intuitive, is less supported and uses operators for multiplication differently. This means that you can't perform matrix multiplications symbollically, but that you will have to use functions from the NumPy library!** 

**1.1.1** a)(0.3 points) Generate (and print) the following vectors using functions from the *NumPy* package in Python: 
*Note: You do not have to print column vectors as columns!*

\begin{equation}
     \textbf{x} = \begin{pmatrix} 
         6 \\
         7 \\
         8 \\
         9 \\
         10 \\
         11 \\
         12
       \end{pmatrix}
     \textbf{y} = \begin{pmatrix} 
         3 \\
         7 \\
         11 \\
         15 \\
         19 \\
         23 \\
         27
       \end{pmatrix}
     \textbf{w} = \begin{pmatrix} 
         1 \\
         1 \\
         0 \\
         0.5 \\
         1 \\
         1.5 \\
         2 \\
         0 \\
         0 
       \end{pmatrix}
     \textbf{s} = \begin{pmatrix}
         100 \\
         98.8 \\
         97.6 \\
         96.4 \\
         95.2
       \end{pmatrix} 
     \textbf{z} = \begin{pmatrix}
         0.7 \\
         1.0 \\
         1.3 \\
         1.6 \\
         1.9 \\
         2.2 \\
         2.5 \\
         2.8
       \end{pmatrix}
  \end{equation}



In [1]:
#Import NumPy
import numpy as np
#You'll have to manually import libraries in the future!

In [2]:
##Generate the vectors in  using Python and NumPy 
x = np.array([6, 7, 8 ,9, 10 ,11, 12])
y = np.array([3, 7, 11 ,15, 19 ,23, 27])
w = np.array([1, 1, 0, 0.5, 1, 1.5, 2, 0, 0])
s = np.array([100, 98.8, 97.6, 96.4, 95.2])
z = np.array([0.7, 1.0, 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

print(x)
print(y)
print(w)
print(s)
print(z)

[ 6  7  8  9 10 11 12]
[ 3  7 11 15 19 23 27]
[1.  1.  0.  0.5 1.  1.5 2.  0.  0. ]
[100.   98.8  97.6  96.4  95.2]
[0.7 1.  1.3 1.6 1.9 2.2 2.5 2.8]


Then compute the following operations:
> b) (0.2 points) **v** = 3**x** + **y**

In [3]:
##Answer to question 1.1.1b
v = 3*x+y
print(v)

[21 28 35 42 49 56 63]


> c) (0.2 points) The dot product between **x** and **y** and name it **q**


In [4]:
##Answer to question 1.1.1c
q = np.dot(x, y)
print(q)

1057


> d) (0.2 points) **t** = pi(**s** + 4) (element wise multiplication)

In [5]:
##Answer to question 1.1.1d
import math
t = math.pi*(s+4)
print(t)

[326.72563597 322.95572479 319.1858136  315.41590242 311.64599124]


> e) (0.2 points) **z** = **z** - 1

In [6]:
##Answer to question 1.1.1e
z = z-1
print(z)

[-0.3  0.   0.3  0.6  0.9  1.2  1.5  1.8]


> f) (0.2 points) replace some values of x, such that the last three values in the vector are 4

In [7]:
##Answer to question 1.1.1f
for c in range(len(x)):
    x[c] = 4
    
print(x)

[4 4 4 4 4 4 4]


> g) (0.2 points) **r** = 2**w** - 5

In [8]:
##Answer to question 1.1.1g
r = 2*w-5
print(r)

[-3. -3. -5. -4. -3. -2. -1. -5. -5.]


**1.1.2** (0.25 points) Generate these matrices:

\begin{equation}
     \textbf{M} = \begin{pmatrix} 
         1 & 2 & 3 \\
         6 & 8 & 4 \\
         6 & 7 & 5          
         \end{pmatrix}
     \textbf{N} = \begin{pmatrix} 
         4 & 6 \\
         7 & 2 \\
         5 & 1
         \end{pmatrix}
     \textbf{P} = \begin{pmatrix} 
         2 & 5 \\
         5 & 5 
         \end{pmatrix}   
\end{equation}

Afterwards try and compute the operations for subquestions *a* up to and including *e* and print the resulting matrix. If some operations yield errors, give the reason as to why that happens.

*A hint: NumPy has functions for matrix operations you can, and should, use! For instance, * **M\*N** * should be calculated with NumPy's `dot` product.*

In [9]:
##Generate the matrices using Python and NumPy
M = np.array ([[1, 2, 3], [6, 8, 4], [6, 7, 5]])
N = np.array([[4, 6], [7, 2], [5, 1]])
P = np.array([[2, 5], [5, 5]])
print(M)
print(N)
print(P)

[[1 2 3]
 [6 8 4]
 [6 7 5]]
[[4 6]
 [7 2]
 [5 1]]
[[2 5]
 [5 5]]


> a. (0.2 points) **A** = **MN** + **N**

In [10]:
##Answer to question 1.1.2a
A = np.add(N, np.dot(M, N))
print(A)

[[ 37  19]
 [107  58]
 [103  56]]


> b. (0.2 points) **B** = **N**<sup>T</sup>**M**

In [11]:
##Answer to question 1.1.2b
B = np.dot((N.transpose()), M)
print(B)

[[76 99 65]
 [24 35 31]]


> c. (0.2 points) **C** = **P**<sup>-1</sup> + **P**

In [12]:
##Answer to question 1.1.2c
C = np.add (np.linalg.inv(P), P)
print(C)

[[1.66666667 5.33333333]
 [5.33333333 4.86666667]]


> d. (0.2 points) **D** = **AC**(**C** + **B**)

In [13]:
##Answer to question 1.1.2d
var1 = np.dot(A, C)
#var2 = np.add(C, B)
#D = np.dot(var1, var2)
#print(D)
print("the 2x2 matrix C cannot be added to the 2x3 matrix B")

the 2x2 matrix C cannot be added to the 2x3 matrix B


> e. (0.2 points) Compute the eigenvalues and eigenvectors of **M**, **N**, and **P** (and print them).

In [14]:
##Answer to question 1.1.2e
matrices = [M, P]
print("For M and P")
for X in matrices:      
    eigenvalues, eigenvectors = np.linalg.eig(X)
    print("Eigenvalues", eigenvalues)
    print("Eigenvectors", eigenvectors)

print("Non-square matrices don't have eigenvalues or eigenvectors")

For M and P
Eigenvalues [-1.26208735 14.26208735  1.        ]
Eigenvectors [[-0.84234218  0.25759308  0.51507875]
 [ 0.38109032  0.68324439 -0.71318597]
 [ 0.38109032  0.68324439  0.47545731]]
Eigenvalues [-1.72015325  8.72015325]
Eigenvectors [[-0.80229293 -0.59693053]
 [ 0.59693053 -0.80229293]]
Non-square matrices don't have eigenvalues or eigenvectors


# Intermezzo: proper scientific plotting practices 

**In this course and many others** you will be asked to make a lot of plots. If you've ever read an academic paper, you'll have noticed that besides axis labels, titles and legends, these also contain a figure description *for each plot*. The idea is that you can 'read' a figure without skimming through the text for the explanation. So these figure descriptions should contain

1. A description in natural language explaining what we're looking at,
2. references to the axis labels if these are not clear immediately, and
3. provide a short answer to the question that it belongs to. 

### Examples:

In [15]:
import matplotlib.pyplot as plt
import numpy as np
numbers = np.arange(100,1001,100)

# Simple plot

plt.plot(numbers)
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.title('Numbers')
plt.show()
print('Figure 1: an example of a simple plot. X axis shows the index of each element, the Y axis shows increasing numbers.')

# a little more complex plot

indices = np.arange(5,15)
plt.scatter(indices,numbers)
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.title('Numbers')
plt.show()
print('Figure 2: an example of a slightly more complex plot, where we explicitely set the values on the X axis. X axis shows the index of each element, the Y axis shows increasing numbers.')


# an incredibly unnecessary complex plot
import seaborn as sns # nicer graphics
sns.set_style('darkgrid')

fig,ax = plt.subplots(3,2,figsize=(8,8)) # create 3 rows of 2 columns of subplots
ax = ax.ravel()

x = np.random.normal(0.1, 1,10) #10 numbers with a mean of 0.1 and a sigma of 1
y = np.random.normal(1, 0.1,10) #10 numbers with a mean of 1 and a sigma of 0.1

ax[0].plot(x,y,'k.') # k means black and . means it should plot dots. Similarly, 'r-' results in a red line and 
                    # 'b--' would result in a blue checkered line.
ax[0].set_title('Random black dots using x and y as coords')
ax[0].set_ylabel('Row 0 of subplots')
ax[1].bar(range(0,10),x,color='orange') #the first argument tells plt where to place the bars, so range(0,10) just puts them on 0,..,9
ax[1].set_title('Vertical bars of x values')

ax[2].barh(range(0,10),y,color='darkblue')
ax[2].set_title('Horizontal bars of y values')
ax[2].set_ylabel('Row 1 of subplots')
from scipy import ndimage 

im = np.zeros((28, 28)) # creates an 28x28 array of zeros
points = 28 * np.random.random((2, 3 ** 2)) # creates 28 random (x,y) pairs that we will use as indices
im[(points[0]).astype(np.int), (points[1]).astype(np.int)] = 1 # sets the value at those indices to 1
im = ndimage.gaussian_filter(im, sigma=28 / (4. * 3)) # puts the array through an image filter that 
                                                        # blurs the 0's and 1's together
blobs = (im > im.mean())*255 # seperates them back into 0's and 1's after blurring 

ax[3].imshow(blobs,cmap='gray') # plots the array as an image, where each pixel corresponds to a 0 or 1 in our array
ax[3].set_title('Blobs in black and white')

ax[4].hist(im.ravel(), bins=12,color='green',rwidth=0.9) # plot the gray values from the array in a histogram with 12 bins
ax[4].set_title('Distribution of grayvalues')
ax[4].set_ylabel('Row 2 of subplots')
ax[4].set_xlabel('Column 0 of subplots')
ax[5].hist(im.ravel(),bins=12, cumulative=True, color='orange',rwidth=0.9,alpha=0.8,label='summed') # plot a see through 
                                                                                # cumulative histogram with alpha
ax[5].hist(im.ravel(), bins=12,color='green',rwidth=0.9,alpha=0.7,label='values') # plot the gray values from the array in a histogram with 12 bins
ax[5].set_title('(Cumulative) Distribution of grayvalues')
ax[5].legend()
ax[5].set_xlabel('Column 1 of subplots')
plt.tight_layout() # makes sure everything fits without overlapping -- try running this cell without this to see the effect

plt.show()

print('Figure 3: an example of a complex plot, which showcases some neat pretty stuff that matplotlib can do! Seaborn is a library that you can use to make your plots look nicer. Subplots are used to create multiple plots within the same figure. First I plotted some random black dots, and then I used the bar functions to plot the same information but more complicated. imshow can be used to plot your array as an image for easy inspection. Here, I created an image of blobs using random numbers and a gaussian blur filter. Histograms are nice for checking distributions, for instance, the distribution of gray values in an image containing blobs!')
sns.reset_orig()

<Figure size 640x480 with 1 Axes>

Figure 1: an example of a simple plot. X axis shows the index of each element, the Y axis shows increasing numbers.


<Figure size 640x480 with 1 Axes>

Figure 2: an example of a slightly more complex plot, where we explicitely set the values on the X axis. X axis shows the index of each element, the Y axis shows increasing numbers.


<Figure size 800x800 with 6 Axes>

Figure 3: an example of a complex plot, which showcases some neat pretty stuff that matplotlib can do! Seaborn is a library that you can use to make your plots look nicer. Subplots are used to create multiple plots within the same figure. First I plotted some random black dots, and then I used the bar functions to plot the same information but more complicated. imshow can be used to plot your array as an image for easy inspection. Here, I created an image of blobs using random numbers and a gaussian blur filter. Histograms are nice for checking distributions, for instance, the distribution of gray values in an image containing blobs!


## 1.2 Principal Component Analysis

**1.2.1** many experimenters have a habit of using Microsoft Excel as their tool to record measurements from experiments. Fortunately Python can read Excel files. Various methods exist, of which the use of the Python library Pandas is arguably one of the easiest for the purpose of Data Mining.

The data used in this exercise is based on data from a chemical sensor obtained from the NanoNose project[1]. The data contains 8 sensors, named by the letters A-H, measuring the concentration of Water, Ethanol, Acetone, Heptane and Pentanol injected into a small gas chamber. The data will be represented in matrix form such that each column contains the 8 sensor measurements (i.e., sensor A-H) of the various compounds injected into the gas chamber.
> a. (0.2 points) Inspect the nanonose.xls file in the Data folder and make sure you understand how the data is stored in Excel.

> *Load the data in python using the Pandas library (use the `read_excel()` function). Make sure you read some of the Pandas documentation! Especially (column) slicing, (row) indexing and dropping are useful commands to get the correct data here.*

> *Make sure to inspect the data first. **You should cut out some rows and columns! You can easily inspect the structure of the Pandas dataframe by printing the `head()` function.***

> *You should see the 8 columns named A-H and the first 5 rows by printing `head()`.*

> *Finally use the `.values` function to cast the Pandas dataframe to a NumPy array called **X**. *

In [16]:
import pandas as pd

#The nanonose.xls file was moved to the directory of the Assignment_1.ipynb file for convenience
df = pd.read_excel('nanonose.xls')
M = df.as_matrix()
print (M)

FileNotFoundError: [Errno 2] No such file or directory: 'nanonose.xls'

> b. (0.3 points) The data resides in what can be seen as an 8-dimensional space. Each dimension (column), corresponds to one of the 8 NanoNose sensors. Multidimensional (>3) data is hard to visualize, as we are unable to plot that many dimensions simultaneously.

> Using the `matplotlib.pyplot` library, plot the attributes A and B against each other. After you have plotted A against B, also plot a few other combinations of attributes. Plot at least 4 different combinations. 

> *Do not forget to label your axes and add a figure description!*

> NOTE: If you want to plot inside the Jupyter notebook without calling `plt.show()` after each plot, use the following command after you imported the `matplotlib.pyplot` library: 
*%matplotlib inline* 

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline


plt.figure(1)

A = df[['A']]
B = df[['B']]
C = df[['C']]
D = df[['D']]
E = df[['E']]
F = df[['F']]
G = df[['G']]
H = df[['H']]


plt.plot(A,B , 'ro', label = "A against B")

plt.title("A plotted against B")
plt.xlabel('A')
plt.ylabel('B')


plt.figure(2)

plt.plot(A,C,'ro')

plt.title("A plotted against C")
plt.xlabel('A')
plt.ylabel('C')


plt.figure(3)

plt.plot(C,D,'ro')

plt.title("C plotted against D")
plt.xlabel('C')
plt.ylabel('D')


plt.figure(4)

plt.plot(D,C, 'ro')

plt.title("D plotted against C")
plt.xlabel('D')
plt.ylabel('C')


1.2.2 Principal Component Analysis, more commonly known as PCA, can be used to visualize high dimensional data. 

> a. (1 point) Explain what PCA is and when it can be used. Make sure to provide an in-depth explanation and note what the drawbacks and limitations are.

--------

_write your answer to 1.2.2 here_

Principle component analaysis is a technique used for dimensionality reduction.
In essence a new coordinate system is found, in which the origin is on the mean if the values and its axis are the principle components, these principle components are the directions of largest variance and ar orthogonal to each other. After this is done the datapoints can be projected onto the coordinate system of the first couple principle components.

It can be used to reduce the number of variables in situations where it is difficult identify the variables to remove. A real-life example could be trying to predict the total number of sales a large retailer might have. In this case, there is a lot of data to consider like for example: Purchasing power, target demographic, advertisement/discounts, inventory expansion and competition. Using PCA to remove the dimensionality makes data faster to process and interpret.

That said there are drawbacks most importantly that PCA can only help in finding linear relations it helps find the direction of this linear data using the orthogonal components, however this obviously does not work for data that is not linearly related. A good example of non-linearly related data is the amount of people helping to do a single task and the time the job takes.
Other drawbacks are that extreme noise might cause PCA to suggest that the noise is the most important relation in the data. And like other dimensionality reduction techniques, removing dimensions makes independant variables less interpretable.

-------

To apply PCA we must first mean center the data. Mean centering means that the mean value for an attribute (i.e. a column) is subtracted from all values for that attribute. 

> b. (0.5 points) Why do we first need to mean center the data before applying PCA?

------
The components calculated in PCA are based on the deviation of the data points, this means that points with higher deviation have a higher weight in the calculation. Essentially when we mean center the data, we lower the standard deviation of our data points. This means that in our calculation all our data points will have the same weight, giviing a much better PCA projection.

-------------

In practice, applying PCA comes down to a series of matrix operations, this is useful, as matrix operations can be applied with little effort and can be computed in relatively little time.

The given data **X** must first be mean centered. This can be easily done by calculating a row vector **μ** containing the mean values of each attribute. Then you can subtract **μ** from **X** (**Y** = **X** - **μ**, where **μ** is subtracted from every row.).

Then, the Singular Value Decomposition (or SVD) of **Y**, the now mean centered data, can be calculated. **Y** = **USV**<sup>T</sup>. In practice, this is often done using the `numpy.linalg.svd()` function.

Using SVD on **Y** yields 3 matrices **U**, **S** and **V**<sup>T</sup>. These are used to project the data onto specific Principal Components (PCs). 

The entire dataset can be projected onto the Principal Components by multiplying **Z** = **Y\*V**, where **Z** indicates the projected data, and **Z[:,0]** indicates the data projected onto the first PC. Alternatively, one could project onto just a subset of all the PCs by indexing in the multiplication. For example: **Z** = **Y\*V[:,0]** would also yield the projection of the data onto the first PC.

_Note that for matrices, the notation **Y\*V** denotes the `dot` product between **Y** and **V**!_

> c. (1 point)  Apply PCA (using the aforementioned method) on the Nanonose data and visualize a scatterplot of the projection of the data onto the first two PCs.

In [ ]:
columns = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
u = np.array([]) # Mean row vector 
for a in columns:
    col = df[[a]]
    u = np.append(u, np.mean(col))

X = np.delete(M, 0, 1)  
X = np.delete(X, 0, 1)  
X = np.delete(X, 0, 1)
X = np.delete(X, 0, 0) # Matrix of only observation

Y = X - u # Mean centered matrix

# For some reason numpy's svd function did not like the matrix constructed here. 
# Therefore we also did the calculations in 'matrixY.xlsx' This is identical to the matrix above.
impY = pd.read_excel('matrixY.xlsx') #This is simply the matrix reimported so columns A-H and mean centered
Y = impY.as_matrix()

u, s, vh = np.linalg.svd(Y)
pca1 = np.dot(Y, vh[:,1]) 
pca2 = np.dot(Y, vh[:,2]) 

# Plotting

plt.plot(pca1,pca2 , 'ro', label = "PCA")
plt.xlabel('pca1')
plt.ylabel('pca2')
plt.title("Projection of the data onto the first two PCs")


> d. (1 point) Alternatively, one could use EigenValue Decomposition, EVD, instead of SVD. What are the similarities and differences between SVD and EVD? Can both be applied in each case?

---
Similarities
Both EVD and SVD are factorizations of matrices, this means the are rotatations of coordinate systems and have independent scaling along each axis. In fact SVD is the generalization of SVD on non-square matrices. In fact the left and right singular vectors of SVD are both orthonormal eigenvectors.

Differences
As said above the SVD vectors are orthonormal, meaning that they represent simple rotations or flips this isn't the case in EVD. On the other hand EVD first and last diagnonal matrices (U in the slides) are each other's inverse, this is not the case in SVD. Lastly in SVD the middle diagonal matrix (capital sigma in the slides) can only be 0 or a positive real number. In EVD the middle diagonal matrix (capital lambda in the slides) can be negative and complex.

Applicability
Eigenvalue decomposition can only applied to square matrices, where SVD can be done on any matrix.

---

PCA attempts to explain as much of the variance in data with as few PCs as possible. The variance explained by each of the PCs **m** can be calculated using the following formula: 
$$\rho_m = 1 - \frac{\|{Y} - {u}_m s_{mm} {v}_m^T\|^2_F}{\|{Y}\|^2_F} = \frac{s_{mm}^2}{\displaystyle \sum_{m'=1}^M s^2_{m'm'}}$$

Which indicates that the variation $\rho$ for a given **m** can be calculated by dividing the squared singular value of component **m** by the sum of all squared singular values. 
> e. (1 point) Calculate the row vector $\rho$ containing all values of $\rho$ for all PCs **m**. Create a bar plot with the variance explained on the Y axis and the number of the PC on the X axis. 

In [ ]:
gar, S, bage = np.linalg.svd(Y)

total = 0
for tot in S:
    total = total + (tot**2)

p = np.array([])
for s in S:
    p = np.append(p, ((s**2)/(total)))
plt.bar([1,2,3,4,5,6,7,8],p)
plt.xlabel('PC')
plt.ylabel('variance')
plt.title("Variance of PCs")

> f. (0.5 points) How much of the variance is explained by the first three PCs?

In [ ]:
total = 0
for var in range(2):
    total = total + p[var]
    
print (total)

The columns of **V** indicate the exact projection of the data onto the PCs. In a way, a PC is nothing other than a linear combination of the original attributes. 
> g. (0.5 points) Which attributes are primarily represented by the first PC? What would cause an observation to have a large negative/positive projection onto the second principal component?

In [ ]:
proj1 = vh[:,1] 
proj2 = vh[:,2]
print(proj1)
print(proj2)

plt.figure(11)
plt.title("A against proj1")
plt.xlabel('cell No.')
plt.ylabel('value')
plt.plot(A, pca1, 'ro')

plt.figure(12)

plt.title("B plot")
plt.xlabel('cell No.')
plt.ylabel('value')
plt.plot(B, 'ro')
plt.figure(13)

plt.title("C plot")
plt.xlabel('cell No.')
plt.ylabel('value')
plt.plot(C, 'ro')
plt.figure(14)

plt.title("D plot")
plt.xlabel('cell No.')
plt.ylabel('value')
plt.plot(D, 'ro')

plt.figure(15)

plt.title("E plot")
plt.xlabel('cell No.')
plt.ylabel('value')
plt.plot(E, 'ro')

plt.figure(16)

plt.title("F plot")
plt.xlabel('cell No.')
plt.ylabel('value')
plt.plot(F, 'ro')

plt.figure(17)

plt.title("G plot")
plt.xlabel('cell No.')
plt.ylabel('value')
plt.plot(G, 'ro')

plt.figure(18)

plt.title("H plot")
plt.xlabel('cell No.')
plt.ylabel('value')
plt.plot(H, 'ro')


----
_write your answer to 1.2.2 here_

-----


## 1.3 Similarity measures

We will use a subset of the data on wild faces described by Berg in 2005 transformed to a total
of 1000 grayscale images of size 40x40 pixels, we will attempt to find faces in the
data base that are the most similar to a given query face. To measure similarity we
will consider the following measures: SMC, Jaccard, Cosine, ExtendedJaccard, and
Correlation. These measures of similarity are described in *Introduction to Data Mining*, page 73-77 and are given by

\begin{eqnarray*}
\textrm{SMC}({x},{y}) & = & \frac{\textrm{Number of matching attribute values}}{\textrm{Number of attributes}} \\
\textrm{Jaccard}({x},{y}) & = & \frac{\textrm{Number of matching presences}}{\textrm{Number of attributes not involved in 00 matches}} \\
\textrm{Cosine}({x},{y}) & = & \frac{{x}^T {y}}{\|{x}\| \|{y}\|} \\
\textrm{ExtendedJaccard}({x},{y}) & = & \frac{{x}^T {y}}{\|{x}\|^2 + \|{y}\|^2 - {x}^T {y}} \\
\textrm{Correlation}({x},{y}) & = & \frac{\textrm{cov}({x},{y})}{\textrm{std}({x}) \textrm{std}({y})}
\\
\end{eqnarray*}
<br>where $\textrm{cov}({x},{y})$ denotes the covariance between ${x}$ and ${y}$ and $\textrm{std}({x})$ denotes the standard deviation of ${x}$.

Notice that the SMC and Jaccard similarity measures only are defined for binary data, i.e., data that takes values in $\{0,1\}$. As the data we analyze is non-binary, the script will transform the data to be binary when calculating these two measures of similarity by setting

$$x_i = \left\{ \begin{array}{ll} 0 & \textrm{if~} x_i < \textrm{median}({x}) \\
                                1 & \textrm{otherwise.} \end{array} \right.$$
                                
### 1.3.1
> a) (0.5 points) Inspect and run the simfaces function from the Toolbox. The function loads the CBCL face database, computes the similarity between a selected query image and all others, and display the query image, the 5 most similar images, and the 5 least similar images. The value of the used similarity measure is shown below each image. Try changing the query image and the similarity measure and see what happens. Which similarity measures produce similar results? Which one gives the best result? Why?

> Give a quick overview of the settings (image number and similarity measure) for each time you run the script. Remember to leave results open!



In [ ]:
from Toolbox.simfaces import simfaces

measures = ['smc', 'jaccard', 'cosine', 'extendedjaccard', 'correlation']
for c in range(4):
    for measure in measures:
        print (measure)
        simfaces((c+1),measure)


----


SMC and jaccard give similar results in the "most similar faces", especially in image 1 and 3. This might be becuase they both use a binary representation of the data.

Correlation seems to give the best results on average, as its least similar pictures often contains non-face pictures or improperly cropped pictures. With its most similar pictures often being most similar in head location, head orientation, skin tone and expression.

----



> b) (0.75 points) We will investigate how scaling and translation impact the following three
similarity measures: Cosine, ExtendedJaccard, and Correlation. Let **x** and **y** be two small vectors of the same size. Let $\alpha$ and $\beta$ be two constants. You can generate these randomly or set them as you see fit. Using Python, calculate the following similarity measures, and check if the statements below are correct.

\begin{eqnarray*}
\textrm{Cosine}(\alpha{x},{y}) & = & \textrm{Cosine}({x},{y}) \\
\textrm{ExtendedJaccard}(\alpha{x},{y}) & = & \textrm{ExtendedJaccard}({x},{y}) \\
\textrm{Correlation}(\alpha{x},{y}) & = & \textrm{Correlation}({x},{y}) \\
\textrm{Cosine}(\beta + {x},{y}) & = & \textrm{Cosine}({x},{y}) \\
\textrm{ExtendedJaccard}(\beta + {x},{y}) & = & \textrm{ExtendedJaccard}({x},{y}) \\
\textrm{Correlation}(\beta + {x},{y}) & = & \textrm{Correlation}({x},{y})
\end{eqnarray*}

> Type `help similarity` or study `similarity.py` to learn about the function that is used to compute the similarity measures. Do not forget to also import similarity.py!

> Even though a similarity measure is theoretically invariant e.g.\ to scaling, it might not be exactly invariant numerically.

> Do not forget to also provide an explanation in addition to the calculations!


In [ ]:
a = 500
b = 1500
x = np.array([6, 7, 8 ,9, 10 ,11, 12])
y = np.array([3, 7, 11 ,15, 19 ,23, 27])

def xty(x, y):  # The dot product of x transposed, with y
    return np.dot(x.transpose(), y)

def covariance(x, y):  # Covariance of 2 vectors as explained in the slides
    total = 0
    for k in range(len(x-1)):
        total = total + ((x[k]-(np.mean(x)))*(y[k]-(np.mean(y))))
    return ((1/len(x))*total)
        
def cosine(x, y):  # Cosine function in python
    return (xty(x, y))/(np.linalg.norm(x)*np.linalg.norm(y))

def extendedjaccard(x, y):  # Extended Jaccard function in python
    return ((xty(x, y))/((np.linalg.norm(x)**2)+(np.linalg.norm(y)**2)-(xty(x, y))))
    
def correlation(x, y):  # Correlation function in python
    return (covariance(x, y))/(np.std(x)*np.std(x))
   
measures = [cosine, extendedjaccard, correlation]


print ("Scaling equalities: ")  # Prints if function is invariant to scaling
for measure in measures:
    print(measure.__name__)
    print (measure (x, y) == measure (a*x, y))

print ("\nTranslation equalities: ")  # Prints if function is invariant to translation
for measure in measures:
    print(measure.__name__)
    print (measure (x, y) == measure ((b+x), y))

---
For the statements, only 2 are correct. Only cosine is invariant to scaling and only correlation is invariant to translation.

This was computed by translating each function to python, then executing them against their scaled on translated counterparts, and checking the resulting equalities.

---