# Assignment 1

## Objective of this assignment
The objective is to get acquainted with the Python language, with emphasis on its scientific and numerical extensions, how data can be imported from other data sources, the linear algebra basics that are needed for this course, visualization using principal component analysis (PCA) and the concept of similarity. Upon completing this exercise it is expected that you:

- Understand how data can be represented as vectors and matrices in numerical Python (NumPy).
- Can apply and interpret principal component analysis (PCA) for data visualization.
- Understand the various measures of similarity such as Jaccard and Cosine similarity and apply similarity measures to query for similar observations.

## ** Important: ** When handing in your homework:
+ Hand in the notebook (and nothing else) named as follows: `StudentName1_snumber_StudentName2_snumber.ipynb`
+ Provide clear and complete answers to the questions below under a separate header (not hidden somewhere in your source code), and make sure to explain your answers / motivate your choices. Add Markdown cells where necessary.
+ Source code, output graphs, derivations, etc., should be included in the notebook.
+ Hand-in: upload to Brightspace.
+ Include name, student number, assignment (especially in filenames)!
+ When working in pairs only one of you should upload the assignment, and report the name of your partner in your filename.
+ Use the Brightspace discussion board or email the student assistants for questions on how to complete the exercises.
+ If you find mistakes/have suggestions/would like to complain about the assigment material itself, please email me [Lisa] at `l.tostrams@science.ru.nl`


## Advised Reading and Exercise Material
**The following on-line materials are recommended:**

- <http://docs.python.org/tutorial> - Introduction into Python environment, syntax and data structures. Recommended reading - sections 1, 2, 3, 4 and 5.
- <https://docs.scipy.org/doc/numpy/user/quickstart.html> - Tutorial introducing the scientific computing in Python, array and matrix operations, indexing and slicing matrices.
- <https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html> - Useful reference to scientific computing in Python if you have previous experience with MATLAB programming.
- <https://www.datacamp.com/courses/intro-to-python-for-data-science> - Simple introduction to Data Science using Python.
- <https://matplotlib.org/> - Documentation and examples related to matplotlib module, which we shall use extensively through the course to visualize data and results.
- Pang-Ning Tan, Michael Steinbach, and Vipin Kumar, **Introduction to Data Mining**, sections 2.1-2.3 + (A) + B.1
- Pang-Ning Tan, Michael Steinbach, and Vipin Kumar, **Introduction to Data Mining**, sections 2.4 + 3.1-3.2 + C.1-C.2


## 1.1 Python and Linear Algebra basics

**For this course we advise to only use NumPy ndarrays to represent vectors and matrices. The numpy.matrix data type, although intuitive, is less supported and uses operators for multiplication differently. This means that you can't perform matrix multiplications symbollically, but that you will have to use functions from the NumPy library!** 

**1.1.1** a)(0.3 points) Generate (and print) the following vectors using functions from the *NumPy* package in Python: 
*Note: You do not have to print column vectors as columns!*

\begin{equation}
     \textbf{x} = \begin{pmatrix} 
         6 \\
         7 \\
         8 \\
         9 \\
         10 \\
         11 \\
         12
       \end{pmatrix}
     \textbf{y} = \begin{pmatrix} 
         3 \\
         7 \\
         11 \\
         15 \\
         19 \\
         23 \\
         27
       \end{pmatrix}
     \textbf{w} = \begin{pmatrix} 
         1 \\
         1 \\
         0 \\
         0.5 \\
         1 \\
         1.5 \\
         2 \\
         0 \\
         0 
       \end{pmatrix}
     \textbf{s} = \begin{pmatrix}
         100 \\
         98.8 \\
         97.6 \\
         96.4 \\
         95.2
       \end{pmatrix} 
     \textbf{z} = \begin{pmatrix}
         0.7 \\
         1.0 \\
         1.3 \\
         1.6 \\
         1.9 \\
         2.2 \\
         2.5 \\
         2.8
       \end{pmatrix}
  \end{equation}



In [48]:
#Import NumPy
import numpy as np
#You'll have to manually import libraries in the future!

In [49]:
##Generate the vectors using Python and NumPy 
x = np.array(range(6,13))
y = np.array([3+4*i for i in range(0,7)])
w = np.array([1,1,0,0.5,1,1.5,2,0,0])
s = np.array([100-1.2*i for i in range(0,5)])
z = np.array([0.7+0.3*i for i in range(0,8)])


# Remember to show your results!
print(x)
print(y)
print(w)
print(s)
print(z)

[ 6  7  8  9 10 11 12]
[ 3  7 11 15 19 23 27]
[1.  1.  0.  0.5 1.  1.5 2.  0.  0. ]
[100.   98.8  97.6  96.4  95.2]
[0.7 1.  1.3 1.6 1.9 2.2 2.5 2.8]


Then compute the following operations:
> b) (0.2 points) **v** = 3**x** + **y**

In [50]:
##Answer to question 1.1.1b

v = 3*x + y

print(v)

[21 28 35 42 49 56 63]


> c) (0.2 points) The dot product between **x** and **y** and name it **q**


In [51]:
##Answer to question 1.1.1c

q = np.dot(x, y)

print(q)

1057


> d) (0.2 points) **t** = pi(**s** + 4) (element wise multiplication)

In [52]:
##Answer to question 1.1.1d
import math

t = math.pi * (s + 4)

print(t)

[326.72563597 322.95572479 319.1858136  315.41590242 311.64599124]


> e) (0.2 points) **z** = **z** - 1

In [53]:
##Answer to question 1.1.1e

z = z - 1

print(z)

[-0.3  0.   0.3  0.6  0.9  1.2  1.5  1.8]


> f) (0.2 points) replace some values of x, such that the last three values in the vector are 4

In [54]:
##Answer to question 1.1.1f

for i in [-1,-2,-3]:
    x[i] = 4

print(x)

[6 7 8 9 4 4 4]


> g) (0.2 points) **r** = 2**w** - 5

In [55]:
r = 2 * w - 5

print(r)


[-3. -3. -5. -4. -3. -2. -1. -5. -5.]


**1.1.2** (0.25 points) Generate these matrices:

\begin{equation}
     \textbf{M} = \begin{pmatrix} 
         1 & 2 & 3 \\
         6 & 8 & 4 \\
         6 & 7 & 5          
         \end{pmatrix}
     \textbf{N} = \begin{pmatrix} 
         4 & 6 \\
         7 & 2 \\
         5 & 1
         \end{pmatrix}
     \textbf{P} = \begin{pmatrix} 
         2 & 5 \\
         5 & 5 
         \end{pmatrix}   
\end{equation}

Afterwards try and compute the operations for subquestions *a* up to and including *e* and print the resulting matrix. If some operations yield errors, give the reason as to why that happens.

*A hint: NumPy has functions for matrix operations you can, and should, use! For instance, * **M\*N** * should be calculated with NumPy's `dot` product.*

In [56]:
##Generate the matrices using Python and NumPy

M = np.array([[1, 2, 3],
              [6, 8, 4],
              [6, 7, 5]])

N = np.array([[4, 6],
              [7, 2],
              [5, 1]])

P = np.array([[2, 5],
              [5, 5]])

print(M)
print(N)
print(P)

[[1 2 3]
 [6 8 4]
 [6 7 5]]
[[4 6]
 [7 2]
 [5 1]]
[[2 5]
 [5 5]]


> a. (0.2 points) **A** = **MN** + **N**

In [57]:
##Answer to question 1.1.2a

A = np.dot(M , N) + N

print(A)

[[ 37  19]
 [107  58]
 [103  56]]


> b. (0.2 points) **B** = **N**<sup>T</sup>**M**

In [58]:
##Answer to question 1.1.2b

B = np.dot(np.transpose(N) , M)

print(B)

[[76 99 65]
 [24 35 31]]


> c. (0.2 points) **C** = **P**<sup>-1</sup> + **P**

In [59]:
##Answer to question 1.1.2c

C = np.linalg.inv(P) + P

print(C)

[[1.66666667 5.33333333]
 [5.33333333 4.86666667]]


> d. (0.2 points) **D** = **AC**(**C** + **B**)

In [60]:
##Answer to question 1.1.2d

E = np.dot(A , C)

D = np.dot(E(C + B))

print(D)

# This gives us an error: ValueError: operands could not be broadcast together with shapes (2,2) (2,3). 
# This is because you cannot add two matrices that have different sizes.

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

> e. (0.2 points) Compute the eigenvalues and eigenvectors of **M**, **N**, and **P** (and print them).

In [ ]:
##Answer to question 1.1.2e

# M eigenvalues and eighevectors
print(np.linalg.eig(M))

# print(np.linalg.eig(N))
# The eigenvalue of N does not compute because it's not a square matrix.

# P eigenvalues and eigenvectors
print(np.linalg.eig(P))

# Intermezzo: proper scientific plotting practices 

**In this course and many others** you will be asked to make a lot of plots. If you've ever read an academic paper, you'll have noticed that besides axis labels, titles and legends, these also contain a figure description *for each plot*. The idea is that you can 'read' a figure without skimming through the text for the explanation. So these figure descriptions should contain

1. A description in natural language explaining what we're looking at,
2. references to the axis labels if these are not clear immediately, and
3. provide a short answer to the question that it belongs to. 

### Examples:

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
numbers = np.arange(100,1001,100)

# Simple plot

plt.plot(numbers)
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.title('Numbers')
plt.show()
print('Figure 1: an example of a simple plot. X axis shows the index of each element, the Y axis shows increasing numbers.')

# a little more complex plot

indices = np.arange(5,15)
plt.scatter(indices,numbers)
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.title('Numbers')
plt.show()
print('Figure 2: an example of a slightly more complex plot, where we explicitely set the values on the X axis. X axis shows the index of each element, the Y axis shows increasing numbers.')


# an incredibly unnecessary complex plot
import seaborn as sns # nicer graphics
sns.set_style('darkgrid')

fig,ax = plt.subplots(3,2,figsize=(8,8)) # create 3 rows of 2 columns of subplots
ax = ax.ravel()

x = np.random.normal(0.1, 1,10) #10 numbers with a mean of 0.1 and a sigma of 1
y = np.random.normal(1, 0.1,10) #10 numbers with a mean of 1 and a sigma of 0.1

ax[0].plot(x,y,'k.') # k means black and . means it should plot dots. Similarly, 'r-' results in a red line and 
                    # 'b--' would result in a blue checkered line.
ax[0].set_title('Random black dots using x and y as coords')
ax[0].set_ylabel('Row 0 of subplots')
ax[1].bar(range(0,10),x,color='orange') #the first argument tells plt where to place the bars, so range(0,10) just puts them on 0,..,9
ax[1].set_title('Vertical bars of x values')

ax[2].barh(range(0,10),y,color='darkblue')
ax[2].set_title('Horizontal bars of y values')
ax[2].set_ylabel('Row 1 of subplots')
from scipy import ndimage 

im = np.zeros((28, 28)) # creates an 28x28 array of zeros
points = 28 * np.random.random((2, 3 ** 2)) # creates 28 random (x,y) pairs that we will use as indices
im[(points[0]).astype(np.int), (points[1]).astype(np.int)] = 1 # sets the value at those indices to 1
im = ndimage.gaussian_filter(im, sigma=28 / (4. * 3)) # puts the array through an image filter that 
                                                        # blurs the 0's and 1's together
blobs = (im > im.mean())*255 # seperates them back into 0's and 1's after blurring 

ax[3].imshow(blobs,cmap='gray') # plots the array as an image, where each pixel corresponds to a 0 or 1 in our array
ax[3].set_title('Blobs in black and white')

ax[4].hist(im.ravel(), bins=12,color='green',rwidth=0.9) # plot the gray values from the array in a histogram with 12 bins
ax[4].set_title('Distribution of grayvalues')
ax[4].set_ylabel('Row 2 of subplots')
ax[4].set_xlabel('Column 0 of subplots')
ax[5].hist(im.ravel(),bins=12, cumulative=True, color='orange',rwidth=0.9,alpha=0.8,label='summed') # plot a see through 
                                                                                # cumulative histogram with alpha
ax[5].hist(im.ravel(), bins=12,color='green',rwidth=0.9,alpha=0.7,label='values') # plot the gray values from the array in a histogram with 12 bins
ax[5].set_title('(Cumulative) Distribution of grayvalues')
ax[5].legend()
ax[5].set_xlabel('Column 1 of subplots')
plt.tight_layout() # makes sure everything fits without overlapping -- try running this cell without this to see the effect

plt.show()

print('Figure 3: an example of a complex plot, which showcases some neat pretty stuff that matplotlib can do! Seaborn is a library that you can use to make your plots look nicer. Subplots are used to create multiple plots within the same figure. First I plotted some random black dots, and then I used the bar functions to plot the same information but more complicated. imshow can be used to plot your array as an image for easy inspection. Here, I created an image of blobs using random numbers and a gaussian blur filter. Histograms are nice for checking distributions, for instance, the distribution of gray values in an image containing blobs!')
sns.reset_orig()

## 1.2 Principal Component Analysis

**1.2.1** many experimenters have a habit of using Microsoft Excel as their tool to record measurements from experiments. Fortunately Python can read Excel files. Various methods exist, of which the use of the Python library Pandas is arguably one of the easiest for the purpose of Data Mining.

The data used in this exercise is based on data from a chemical sensor obtained from the NanoNose project[1]. The data contains 8 sensors, named by the letters A-H, measuring the concentration of Water, Ethanol, Acetone, Heptane and Pentanol injected into a small gas chamber. The data will be represented in matrix form such that each column contains the 8 sensor measurements (i.e., sensor A-H) of the various compounds injected into the gas chamber.
> a. (0.2 points) Inspect the nanonose.xls file in the Data folder and make sure you understand how the data is stored in Excel.

> *Load the data in python using the Pandas library (use the `read_excel()` function). Make sure you read some of the Pandas documentation! Especially (column) slicing, (row) indexing and dropping are useful commands to get the correct data here.*

> *Make sure to inspect the data first. **You should cut out some rows and columns! You can easily inspect the structure of the Pandas dataframe by printing the `head()` function.***

> *You should see the 8 columns named A-H and the first 5 rows by printing `head()`.*

> *Finally use the `.values` function to cast the Pandas dataframe to a NumPy array called **X**. *

In [ ]:
import pandas as pd

data = pd.read_excel(r'C:\Users\eddib\Documents\University\1920\Data Mining\Assignments Data Mining\Assignment_1\Data\nanonose.xls')

print(data.head())

X = data.values

print(X)

> b. (0.3 points) The data resides in what can be seen as an 8-dimensional space. Each dimension (column), corresponds to one of the 8 NanoNose sensors. Multidimensional (>3) data is hard to visualize, as we are unable to plot that many dimensions simultaneously.

> Using the `matplotlib.pyplot` library, plot the attributes A and B against each other. After you have plotted A against B, also plot a few other combinations of attributes. Plot at least 4 different combinations. 

> *Do not forget to label your axes and add a figure description!*

> NOTE: If you want to plot inside the Jupyter notebook without calling `plt.show()` after each plot, use the following command after you imported the `matplotlib.pyplot` library: 
*%matplotlib inline* 

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

df = pd.DataFrame(data)

df.plot.scatter(x='A',y='B',color='red')
plt.ylabel("Sensor A")
plt.xlabel("Sensor B")
plt.title("Attributes A and B plotted against each other")
df.plot.scatter(x='A',y='C',color='orange')
plt.ylabel("Sensor A")
plt.xlabel("Sensor C")
plt.title("Attributes A and C plotted against each other")
df.plot.scatter(x='F',y='H',color='yellow')
plt.ylabel("Sensor F")
plt.xlabel("Sensor H")
plt.title("Attributes F and H plotted against each other")
df.plot.scatter(x='B',y='G',color='green')
plt.ylabel("Sensor B")
plt.xlabel("Sensor G")
plt.title("Attributes B and G plotted against each other")
df.plot.scatter(x='C',y='F',)
plt.ylabel("Sensor C")
plt.xlabel("Sensor F")
plt.title("Attributes C and F plotted against each other")


1.2.2 Principal Component Analysis, more commonly known as PCA, can be used to visualize high dimensional data. 

> a. (1 point) Explain what PCA is and when it can be used. Make sure to provide an in-depth explanation and note what the drawbacks and limitations are.

--------

PCA is something that is used for feature extraction. Basically how it works is that you put in your input variables, and then PCA eliminates the less important variables and retains the more important variables. Something that is notable about PCA is that the variables you keep after using PCA are all independent of one another.
PCA can be used to lower the size of a large, multi-dimensional, data set.
The biggest drawback of PCA is that you lose a lot of information, because you only end up taking the more valuable data into account. 

-------

To apply PCA we must first mean center the data. Mean centering means that the mean value for an attribute (i.e. a column) is subtracted from all values for that attribute. 

> b. (0.5 points) Why do we first need to mean center the data before applying PCA?

------

This is because, after you use PCA, you will want to visualise your data diagonally in a graph. We want to be able to flip our graph and compare it to other graphs, which means that we want to center our data. 

-------------

In practice, applying PCA comes down to a series of matrix operations, this is useful, as matrix operations can be applied with little effort and can be computed in relatively little time.

The given data **X** must first be mean centered. This can be easily done by calculating a row vector **μ** containing the mean values of each attribute. Then you can subtract **μ** from **X** (**Y** = **X** - **μ**, where **μ** is subtracted from every row.).

Then, the Singular Value Decomposition (or SVD) of **Y**, the now mean centered data, can be calculated. **Y** = **USV**<sup>T</sup>. In practice, this is often done using the `numpy.linalg.svd()` function.

Using SVD on **Y** yields 3 matrices **U**, **S** and **V**<sup>T</sup>. These are used to project the data onto specific Principal Components (PCs). 

The entire dataset can be projected onto the Principal Components by multiplying **Z** = **Y\*V**, where **Z** indicates the projected data, and **Z[:,0]** indicates the data projected onto the first PC. Alternatively, one could project onto just a subset of all the PCs by indexing in the multiplication. For example: **Z** = **Y\*V[:,0]** would also yield the projection of the data onto the first PC.

_Note that for matrices, the notation **Y\*V** denotes the `dot` product between **Y** and **V**!_

> c. (1 point)  Apply PCA (using the aforementioned method) on the Nanonose data and visualize a scatterplot of the projection of the data onto the first two PCs.

In [ ]:
A = X[1:X.shape[0],3:X.shape[1]]
mu = A.mean(0)
#print(mu)

Y = (A - mu).astype(np.float32)
U,S,Vt = np.linalg.svd(Y)
V = Vt.transpose()
#print(V)

Z=Y.dot(V)
plt.scatter(Z[:,0],Z[:,1])
print(S)

> d. (1 point) Alternatively, one could use EigenValue Decomposition, EVD, instead of SVD. What are the similarities and differences between SVD and EVD? Can both be applied in each case?

---

_write your answer to 1.2.2 here_
They cannot both be applied in any case, since they are fundamentally different. 
EVD and SVD have the same general goal. A very important difference though, is that EVD only exists for square matrices. Another difference is that the U and V you get from SVD are always orthogonal, while this isn't the case for EVD.

---

PCA attempts to explain as much of the variance in data with as few PCs as possible. The variance explained by each of the PCs **m** can be calculated using the following formula: 
$$\rho_m = 1 - \frac{\|{Y} - {u}_m s_{mm} {v}_m^T\|^2_F}{\|{Y}\|^2_F} = \frac{s_{mm}^2}{\displaystyle \sum_{m'=1}^M s^2_{m'm'}}$$

Which indicates that the variation $\rho$ for a given **m** can be calculated by dividing the squared singular value of component **m** by the sum of all squared singular values. 
> e. (1 point) Calculate the row vector $\rho$ containing all values of $\rho$ for all PCs **m**. Create a bar plot with the variance explained on the Y axis and the number of the PC on the X axis. 

In [ ]:
pcs = range(0, len(S))
rho = []
Ssq = []
for x in range (0, len(S)):
    Ssq.append((S[x])^2)
    
SumSsq = sum(Ssq) 

for y in range (0, len(S)):
    rho.append(Ssq[y]/SumSsq)

plt.bar(pcs, rho, align='center', alpha=0.5)
plt.xlabel('Number of PCs')
plt.ylabel('Variance(𝜌)')
plt.title('The variance plotted against the number of the PC')

I'm getting the following error here: TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
and I'm not sure why, because I feel like I should be able to index S just fine.

> f. (0.5 points) How much of the variance is explained by the first three PCs?

I would say a lot of the variance is explained by the first three PCs, since these have the most variance.

The columns of **V** indicate the exact projection of the data onto the PCs. In a way, a PC is nothing other than a linear combination of the original attributes. 
> g. (0.5 points) Which attributes are primarily represented by the first PC? What would cause an observation to have a large negative/positive projection onto the second principal component?

----
_write your answer to 1.2.2 here_

-----


## 1.3 Similarity measures

We will use a subset of the data on wild faces described by Berg in 2005 transformed to a total
of 1000 grayscale images of size 40x40 pixels, we will attempt to find faces in the
data base that are the most similar to a given query face. To measure similarity we
will consider the following measures: SMC, Jaccard, Cosine, ExtendedJaccard, and
Correlation. These measures of similarity are described in *Introduction to Data Mining*, page 73-77 and are given by

\begin{eqnarray*}
\textrm{SMC}({x},{y}) & = & \frac{\textrm{Number of matching attribute values}}{\textrm{Number of attributes}} \\
\textrm{Jaccard}({x},{y}) & = & \frac{\textrm{Number of matching presences}}{\textrm{Number of attributes not involved in 00 matches}} \\
\textrm{Cosine}({x},{y}) & = & \frac{{x}^T {y}}{\|{x}\| \|{y}\|} \\
\textrm{ExtendedJaccard}({x},{y}) & = & \frac{{x}^T {y}}{\|{x}\|^2 + \|{y}\|^2 - {x}^T {y}} \\
\textrm{Correlation}({x},{y}) & = & \frac{\textrm{cov}({x},{y})}{\textrm{std}({x}) \textrm{std}({y})}
\\
\end{eqnarray*}
<br>where $\textrm{cov}({x},{y})$ denotes the covariance between ${x}$ and ${y}$ and $\textrm{std}({x})$ denotes the standard deviation of ${x}$.

Notice that the SMC and Jaccard similarity measures only are defined for binary data, i.e., data that takes values in $\{0,1\}$. As the data we analyze is non-binary, the script will transform the data to be binary when calculating these two measures of similarity by setting

$$x_i = \left\{ \begin{array}{ll} 0 & \textrm{if~} x_i < \textrm{median}({x}) \\
                                1 & \textrm{otherwise.} \end{array} \right.$$
                                
### 1.3.1
> a) (0.5 points) Inspect and run the simfaces function from the Toolbox. The function loads the CBCL face database, computes the similarity between a selected query image and all others, and display the query image, the 5 most similar images, and the 5 least similar images. The value of the used similarity measure is shown below each image. Try changing the query image and the similarity measure and see what happens. Which similarity measures produce similar results? Which one gives the best result? Why?

> Give a quick overview of the settings (image number and similarity measure) for each time you run the script. Remember to leave results open!



In [ ]:
from Toolbox.simfaces import simfaces
simfaces(4, 'correlation')

# ----

_write your answer to 1.3.1 here_
The image number i determines the query image you use, that will be inspected by the algorithm. 
The smc similarity measure is very specific about skin tone, but it seems to disregard lighting. The similar images are similar in brightness. even if their skintone is actually not that similar.
I can't really tell what Jaccard bases the similarity off of. Both the most and least similar images seem almost random to me.
The same goes for ExtendedJaccard.
The cosine similarity measure seems to mostly look at the background color, when the query image is an image with a white background the most similar images are those with a white background and the least similar are with a black background, regardless of how similar the face actually is.
I'd say the correlation similarity measure is the best one, as the similar results are really the most similar, they have a similar face shape and are wearing similar clothing.

----



> b) (0.75 points) We will investigate how scaling and translation impact the following three
similarity measures: Cosine, ExtendedJaccard, and Correlation. Let **x** and **y** be two small vectors of the same size. Let $\alpha$ and $\beta$ be two constants. You can generate these randomly or set them as you see fit. Using Python, calculate the following similarity measures, and check if the statements below are correct.

\begin{eqnarray*}
\textrm{Cosine}(\alpha{x},{y}) & = & \textrm{Cosine}({x},{y}) \\
\textrm{ExtendedJaccard}(\alpha{x},{y}) & = & \textrm{ExtendedJaccard}({x},{y}) \\
\textrm{Correlation}(\alpha{x},{y}) & = & \textrm{Correlation}({x},{y}) \\
\textrm{Cosine}(\beta + {x},{y}) & = & \textrm{Cosine}({x},{y}) \\
\textrm{ExtendedJaccard}(\beta + {x},{y}) & = & \textrm{ExtendedJaccard}({x},{y}) \\
\textrm{Correlation}(\beta + {x},{y}) & = & \textrm{Correlation}({x},{y})
\end{eqnarray*}

> Type `help similarity` or study `similarity.py` to learn about the function that is used to compute the similarity measures. Do not forget to also import similarity.py!

> Even though a similarity measure is theoretically invariant e.g.\ to scaling, it might not be exactly invariant numerically.

> Do not forget to also provide an explanation in addition to the calculations!


In [ ]:
from Toolbox.similarity import similarity
import random

x = np.array([1, 5, 3.5, 8, 14, 66])
y = np.array([55, 5.5, 5, 11, 1, 9])

alpha = random.randint(0,100)
beta = random.randint(0,100)

a=similarity(alpha*x, y, 'cos')
b=similarity(x, y, 'cos')
print(a-b)

c=similarity(alpha*x, y, 'ext')
d=similarity(x, y, 'ext')
print(c-d)

e=similarity(alpha*x, y, 'cor')
f=similarity(x, y, 'cor')
print(c-d)

g=similarity(beta + x, y, 'cos')
b=similarity(x, y, 'cos')
print(g-b)

h=similarity(beta + x, y, 'ext')
d=similarity(x, y, 'ext')
print(h-d)

i=similarity(beta + x, y, 'cor')
f=similarity(x, y, 'cor')
print(i-d)



---

_write your answer to 1.3.1 here_
What I found out is that all of the statements are correct except for the last and the third to last statement. It is obvious that if you multiply one vector by a constant, it will still be as similar to another vector as it was before.
The interesting thing we found out is that the cosine similarity measure and the correlation similarity measure change when you add a constant to one of the vectors, but not with the extended jaccard similarity measure.


---